### ISSUE TITLE
Add logging and profiling settings.

### ISSUE THREAD

**Issue by jortel** [konveyor/forklift-operator#108]
Add optional properties for the following environment variables:
- LOG_LEVEL: Set the verbosity.
- PROFILE_KIND: Kind of profile (memory|cpu|mutex).
- PROFILE_PATH: Profiler output directory.
- PROFILE_DURATION: The duration (minutes) the profiler will collect data. (0=indefinately)

when specified, would be set on both (inventory, controller) containers.

Also, please mount an additional (profiler) EmptyDir in the pod for both containers and mount in: /var/cache/profiler.

**Comment by fbladilo** [comment]
@jortel Should we have defaults be for these vars and allow changes to be made via CR? Or just react when they injected on the CR and bounce the controller pod?

**Comment by jortel** [comment]
No defaults and just set the environment variables when the CR is edited and properties specified.
