### ISSUE TITLE
Operator does not work on Openshift 4.8

### ISSUE THREAD

**Issue by dondsmithtx** [konveyor/forklift-operator#199]
I have attempted to install this Operator on two different Openshift 4.8 platforms.  Both of them give authentication failed when logging into the "virt" route after creating the forklift controller.  I did validate that I was a part of the cluster-admin group when verifying.

**Comment by fabiendupont** [comment]
@dondsmithtx, which version of the operator have you used? On OpenShift 4.8, we only tested Forklift 2.1.0.

**Comment by dondsmithtx** [comment]
I'm trying 2.1.0  and I also tried 2.0.0.  I did find an error in the Forklift UI container log:

`Access Token Error Client request error: unable to verify the first certificate`

I tried our Kibana endpoint which uses the same credentials and it is still working.

**Comment by dondsmithtx** [comment]
I'm going to close this issue as it is UI specific. I opened an issue in forklift-ui with a different username.
